### ISSUE TITLE
delete_table shows result data as insert_table

### ISSUE THREAD

**Issue by ShubhankarKG** [spaceuptech/mission-control#148]
In mission control, while previewing mutations, this is what is shown to us
![Screenshot from 2020-06-19 20-03-48](https://user-images.githubusercontent.com/50791000/85144002-29738180-b268-11ea-9fd0-44e3f6adeeea.png)

I believe that the right hand side should also be *delete_table*.

I also think that this is due to this code in utils.js/generateQueries :
```javascript
queries.delete.res = removeRegex(`{ 
      "data":{ 
        "insert_${colName}":{ 
          "status": 200
        }
       }
      }`, 1)
```

**Comment by HeyItsJs** [comment]
Thanks @ShubhankarKG. This is fixed in `v0.19.0` plus many more exciting features to come inside that queries page in `v0.19.0` like a play button 😀

Also `spaceuptech/space-cloud` is the repo where we create all issues now. Be it regarding mission control or docs or gateway
